"""
MindWork — Report Engine
CONFIDENTIAL - PRIVATE REPOSITORY - NOT FOR PUBLIC DISTRIBUTION
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

from config.settings import config
from logging_system import get_logger, LogStatus, LogAction
from mindwork.analyser import AnalysisResult

if TYPE_CHECKING:
    from agent_manager.manager import AgentManager

log = get_logger("mindwork.reporter")


class ReportEngine:
    """
    Converts an AnalysisResult into:
      • machine-readable JSON  → <report_dir>/report_<ts>.json
      • human-readable Markdown → <report_dir>/report_<ts>.md
    All file writes are authorised through AgentManager.
    """

    def __init__(self, agent: "AgentManager") -> None:
        self._agent      = agent
        self._report_dir = Path(config.mindwork.report_output_dir)
        self._report_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, result: AnalysisResult) -> tuple[Path, Path]:
        """Returns (json_path, md_path)."""
        ts_str   = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        stem     = f"report_{ts_str}"
        json_out = self._report_dir / f"{stem}.json"
        md_out   = self._report_dir / f"{stem}.md"

        # JSON
        safe_json = self._agent.request_file_write(str(json_out))
        safe_json.write_text(
            json.dumps(result.to_dict(), indent=2, default=str),
            encoding="utf-8",
        )

        # Markdown
        safe_md = self._agent.request_file_write(str(md_out))
        safe_md.write_text(self._render_markdown(result), encoding="utf-8")

        log.info(
            f"Report generated: {stem}",
            action=LogAction.REPORT, status=LogStatus.OK,
            extra={"json": str(safe_json), "md": str(safe_md)},
        )
        return safe_json, safe_md

    # ── Markdown renderer ─────────────────────────────────────────────────────

    def _render_markdown(self, r: AnalysisResult) -> str:
        dt = datetime.fromtimestamp(r.analysis_ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        score_emoji = "🟢" if r.score >= 80 else "🟡" if r.score >= 50 else "🔴"

        lines = [
            f"# WorkMind Analysis Report",
            f"",
            f"> **CONFIDENTIAL** — Internal use only. Not for public distribution.",
            f"",
            f"| Field | Value |",
            f"|---|---|",
            f"| Generated | {dt} |",
            f"| Node | {config.node.node_id} |",
            f"| Root | `{r.snapshot_root}` |",
            f"| Health Score | {score_emoji} **{r.score:.0f} / 100** |",
            f"| Total Files | {r.total_files:,} |",
            f"| Total Size | {r.total_size_gb:.3f} GB |",
            f"| Average File Size | {r.avg_file_size_bytes/1024:.1f} KB |",
            f"",
        ]

        # Extensions
        lines += ["## Top Extensions by File Count", ""]
        for ext, count in list(r.top_extensions_by_count.items())[:10]:
            bar = "█" * min(40, int(count / max(r.top_extensions_by_count.values()) * 40))
            lines.append(f"- `{ext:12s}` {bar} {count:,}")
        lines.append("")

        # Anomalies
        lines += ["## Anomalies Detected", ""]
        if r.anomalies:
            for a in r.anomalies:
                sev_icon = {"high": "🔴", "medium": "🟡", "low": "🔵"}.get(a.severity, "⚪")
                lines += [
                    f"### {sev_icon} {a.anomaly_type.replace('_', ' ').title()}",
                    f"- **Severity**: {a.severity}",
                    f"- **Detail**: {a.description}",
                    f"- **Suggested action**: {a.suggestion}",
                    "",
                ]
        else:
            lines.append("_No anomalies detected._\n")

        # Suggestions
        lines += ["## Optimisation Suggestions", ""]
        if r.suggestions:
            for s in r.suggestions:
                lines.append(f"- {s}")
        else:
            lines.append("_No additional suggestions._")
        lines.append("")

        lines += [
            "---",
            f"*Generated by WorkMind {config.node.node_id} · {dt}*",
        ]

        return "\n".join(lines)
